### ISSUE TITLE
Save the trainability status of layers in JSON

### ISSUE THREAD

**Issue by mkaze** [JetBrains/KotlinDL#107]
Am I correct in saying that currently when the configuration of the model is saved as JSON, the `trainable` config parameter is always saved as `true` even if the layer is actually frozen (i.e. `layer.isTrainable == false`)? If so, shouldn't it be fixed?

On a related note, similar to Keras, isn't it better to do some refactoring and introduce a new method like `getConfig` for the base `Layer` (and possibly overridden by subclassed layers to add additional layer-specific configs) which then could be used for obtaining config of a layer (instead of creating isolated functions in `ModelSaver.kt`)?

**Comment by zaleslaw** [comment]
Regarding your first question, yes, it looks like a bug, I suppose there is could a few missed things here.
At this moment no good unit test for Model export/import, it's covered by integration test only.

If you wish, you could propose a PR or I could convert it to the good newbie ticket (to attract new contributors), believe me, we could stay some things for them:)

Regarding your proposal. The current solution is not ideal, I see and growing fast. Probably the LayerConfig and the whole config package should be hierarchical instead of the current plain solution (but it's done due to easy generation via JSON with https://github.com/wuseal/JsonToKotlinClass project).

Also good to keep separately the serialization/deserialization of layers and models from the core layer code and grouped logically together. It could be reached with extension functions in Kotlin.

Could we move the second part to the discussions chapter of this repository and continue there. 
Also need to decide, will it be the only one ser-deser approach based on Keras json config or it will be extended.

**Comment by mkaze** [comment]
> I could convert it to the good newbie ticket (to attract new contributors), believe me, we could stay some things for them:)

:smiley: Yeah, that sounds good to me!

> Could we move the second part to the discussions chapter of this repository and continue there.
> Also need to decide, will it be the only one ser-deser approach based on Keras json config or it will be extended.

Yeah, agreed; this should be further discussed to find a good approach.

**Comment by zaleslaw** [comment]
So, it's ok, I labeled it with the "good first issue", I think it will be taken during the summer.

**Comment by dosier** [comment]
Hi, can I do this? 

If so,  should for each type of `Layer` it's corresponding `LayerConfig` set the `trainable` parameter? Or can it be ignored for certain layer types? 

Also are there any guidelines on contributing? I am not very familiar with contributing to an open source project.

**Comment by zaleslaw** [comment]
@dosier Feel free to take this ticket.
This project is not mature enough, and some important parts like guidelines on contributing are missed, so I'll add them in the nearest future; thanks for the advice.

Regarding the ticket: I suggest saving trainable status for all layers when we serialize the model.

**Comment by zaleslaw** [comment]
Great job @dosier congrats you with the first contribution
