### ISSUE TITLE
getOptimizerName convert function to property

### ISSUE THREAD

**Issue by quickstep24** [JetBrains/KotlinDL#29]
Convert function to property
`public abstract fun getOptimizerName(): String`
=>
`public abstract val optimizerName: String`
in `Optimimizer.kt`

**Comment by zaleslaw** [comment]
@quickstep24 agree, with this change to be more Kotlin-idiomatic. If you want, you could create a PR for this and same cases

**Comment by LostMekka** [comment]
I would like to do this, but I have a question: Should this be done while keeping and deprecating the existing `getXyz` methods? In my own projects I only start to use the proper deprecation cycle at 1.0.0 and beyond, but there are many different opinions about that ^^

**Comment by LostMekka** [comment]
And the next question: Structural search revealed things like:
https://github.com/JetBrains/KotlinDL/blob/b1c89e5cc1ce0c873b06e183d15d28c1f819a41c/api/src/main/kotlin/org/jetbrains/kotlinx/dl/api/core/layer/Layer.kt#L82-L84
Judged by the name alone, this is also a getter which could be a `val` property instead, but the implementations do some considerable work there. Should I leave them as they are, or convert them too? Personally, I tend to shy away from method names that look like getters/setters, because getters/setters/properties often look like very cheap operations and this might confuse people. @zaleslaw What is your take on this?

**Comment by zaleslaw** [comment]
@LostMekka no worry about deprecation, feel free to remove methods and convert to properties. But I'm not sure about getWeigths - the idea was to have an abstract method that should be overridden in each layer and sometimes it has a very large body. Maybe you have any idea about renaming this method?

**Comment by LostMekka** [comment]
I'm not sure there either. How about fetchWeights, readWeights, or maybe extractWeights? I don't feel very competent in this particular domain, so I don't know which word would fit best. 😅
